export const BACKGROUND = '#F2F2F2';
export const CARD_BACKGROUND = '#012326';
export const CALENDAR_BACKGROUND = '#97A4A6';
export const CALENDAR_ACTIVE_BACKGROUND = '#587073';
export const LIGHT_TEXT = '#97A4A6';
export const DARK_TEXT = '#012326';

export default {
  BACKGROUND,
  CARD_BACKGROUND,
  CALENDAR_BACKGROUND,
  CALENDAR_ACTIVE_BACKGROUND,
  LIGHT_TEXT,
  DARK_TEXT,
};
